### ISSUE TITLE
Not work on 0.85 ?

### ISSUE THREAD

**Issue by ThomasTerrier** [pluginsGLPI/simcard#10]
Good Morning,

I tried to install the SIMCARD on the 085.4. This message is displayed: This plugin requires GLPI >= 0.84 and GLPI < 0.85 ". I could get around this issue by modifying the maximum version on the setup.php folder. 

The setup has succeeded, however, no link seems to appear in the menus and the "simcard" tab on phones is empty. 

I would like to know if you plan on developping this plugin for the  0.85.4 version. 

Thank you in advance

**Comment by orthagh** [comment]
Hello.

This plugin will be available soon (in september).

Watch the repo update.

Regards

**Comment by ThomasTerrier** [comment]
Hello, 

Thank you for your answer. 

Regards,

**Comment by btry** [comment]
Hi

the plugin is compatible with GLPI 0.85.x . You may download and test it : https://github.com/pluginsGLPI/simcard/releases
