### ISSUE TITLE
Add nbr of () in 'Associated items' tab of a simcard

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/simcard#13]
1.4 for 0.85
In 'Associated items' tab of a Simcard is listed the element to which the simcard is linked (computer or telephone or device).
Between parentheses (), add the nbr of associated items (in principle <= 1)

**Comment by blerohellec** [comment]
Same for the Simcards tab of a computer/device/phone

**Comment by blerohellec** [comment]
OK for the 1st point.
KO for the 2nd

**Comment by blerohellec** [comment]
Both Add an item in the 'Associated items' tab of a Simcard, or Add a Simcard in the Simcards tab of a computer/phone/device now fails when pressing the button Add.
PHP error hereafter
  *** PHP Catchable Fatal Error(4096): Argument 1 passed to PluginSimcardSimcard_Item::countForItem() must be an instance of CommonDBTM, integer given, called in /var/www/glpi085/plugins/simcard/inc/simcard_item.class.php on line 76 and defined
  Backtrace :
  ...5/plugins/simcard/inc/simcard_item.class.php:83 
  ...5/plugins/simcard/inc/simcard_item.class.php:76 PluginSimcardSimcard_Item::countForItem()
  .../plugins/simcard/front/simcard_item.form.php:38 PluginSimcardSimcard_Item->can()

**Comment by dethegeek** [comment]
Association restored, and count should be trustful.

**Comment by blerohellec** [comment]
OK. Corrected
