### ISSUE TITLE
'Serial Number' not translated in 'Sim Card' tab of a computer

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/simcard#14]
1.4 for 0.85
In 'Sim Cards' tab of a computer/telephone/device, the title of the column 'Serial Number' is not translated !

**Comment by blerohellec** [comment]
in inc/simcard_item.class.php, line 230, Number is written with an uppercase, where it should be a lower..
Same in 'Associated items' tab of a Sim Card, where 'Serial Number' & 'Inventory Number' are not translated. See line 152 & 153

**Comment by dethegeek** [comment]
All of these are fixed. In a computer/telephone/device view, "Serial Number" becomes IMSI, to be consistent with the main tab ot a simcard.

**Comment by blerohellec** [comment]
Even better. Thx
