### ISSUE TITLE
Error with 'Ignored values for uniqueness' dropdown when plugin disabled

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/simcard#15]
1.4 for 0.85
Create a record in 'Ignored values for uniqueness' dropdown for Type = 'Sim card'.
Then disable the plugin -> Fatal error: Call to a member function getSearchOptionByField() on a non-object in /var/www/glpi085/inc/fieldblacklist.class.php on line 123.
Same when plugin is Uninstalled, because cleaning is not completely done.

**Comment by dethegeek** [comment]
Is the bug still here ?

**Comment by blerohellec** [comment]
Yes, it is

**Comment by blerohellec** [comment]
Given that the 'Ignored value for uniqueness' is a common dropdown, consider that this issue is maybe to be reported to the GLPI level.
Note that the same error occurs with other plugins : Racks, Orders...
I don't know any other example of common dropdowns including plugin data.
So, a solution at GLPI level is maybe the best solution.

**Comment by dethegeek** [comment]
I could not reproduce the bug. Which version of GLPI did you use ?

**Comment by blerohellec** [comment]
The error occurs only when 'Field' and/or 'Value' are part of the view of the dropdown 'Ignored value for uniqueness'.
With any of the other information, even 'Type', there is no error.

**Comment by btry** [comment]
Several plugins are affected by the same issue, needs investigation in GLPI first.

**Comment by blerohellec** [comment]
I create an issue on GLPI project

**Comment by btry** [comment]
Ok, thank you.
