### ISSUE TITLE
Cleaning of tables not complete on Uninstall

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/simcard#16]
1.4 for 0.85
On plugin uninstall, table glpi_fieldblacklists (Ignored values for uniqueness) is not cleaned.
Same with table glpi_dropdowntranslations (translations of the 4 plugin dropdowns).

**Comment by blerohellec** [comment]
Same with glpi_contracts_items (link with contracts)

**Comment by blerohellec** [comment]
Same with the 3 displaypreferences added to phone/computer/device list (num between 10126 and 10135)

**Comment by dethegeek** [comment]
All these tables should be cleaned now. Waiting for your confirmation before closing.

**Comment by blerohellec** [comment]
Everything's OK. Thx
