### ISSUE TITLE
Notes have disappeared in v 1.4

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/simcard#17]
v1.4 for 0.85
Until v1.3 for 0.84, Simcards had Notes (like most of the itemtypes managed by GLPI).
Notes have disappeared in v1.4.

**Comment by dethegeek** [comment]
Notepad has been restored. 
- migration of old data
- the profile used to install the plugin has the rights for read and update notes
- on upgrade : notes are read if profiles have read access to simcards; and read/write if they got write access to simcards)

I'm waiting for your review.

**Comment by blerohellec** [comment]
upgrade of profile : KO. if the profile has the UPDATE right, the READNOTE right is added twice !
Cleaning on Notes : KO. On simcard permanent deletion, and plugin uninstall, the table glpi_notepads is not cleaned.

**Comment by dethegeek** [comment]
You're right. Cleanup was planned next week, so here it is.

**Comment by blerohellec** [comment]
upgrade of profiles : OK
Cleaning of Notes:
- on uninstall : it works, but I think it's more elegant to simply add the Notepad itemtype in the array (line 651)

**Comment by dethegeek** [comment]
Yes, you're right. I'll refactor the code this way. I guess Infocom should
be cleaned the same way.

2015-09-05 9:43 GMT+02:00 blerohellec <notifications@github.com>:

**Comment by dethegeek** [comment]
Now the notepad should be correctly implemented

**Comment by blerohellec** [comment]
Remains to clean its notes when a Simcard is permanently deleted.

**Comment by btry** [comment]
I'm waiting for your review

**Comment by blerohellec** [comment]
OK
