### ISSUE TITLE
Php Errors on upgrade from v1.3 to 1.4

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/simcard#18]
Upgrading from v1.3 (0.84) to v1.4 (0.85), I got many php errors related to profiles upgrade.
As a consequence, after an upgrade, rights were lost.

**Comment by dethegeek** [comment]
Can you provide logs of these errors ?

**Comment by dethegeek** [comment]
I think I found your issue; Can you check the upgrade process with the latest revision and report back ?

**Comment by blerohellec** [comment]
No longer errors. Thx
