### ISSUE TITLE
Error in upgrading profile rights

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/simcard#23]
1.3 (0.84) to 1.4 (0.85)
In v 1.3, rights were this way
- Simcard: r/w/_
- associable items to a ticket : Yes/No
1 record per profile in table glpi_simcard_profiles.

The upgrade creates 2 records per profile in table glpi_profilerights:
- one where name = simcard:simcard (w -> 31) -> Correct
- one where name = simcard:open-ticket (Yes -> 1) -> NOT CORRECT
On screen, Admin > Profiles > tab Simcard, the right 'associable to a ticket' is NOT ticked.
Indeed, the new profile mngt system in 0.85 expects only 1 record per profile for all rights related to Simcard. And the result of upgrading (w + Yes) should be 63.

**Comment by dethegeek** [comment]
still more work on a fresh install of the plugin.

**Comment by dethegeek** [comment]
Profiles should upgrade/install as expected, and tickets association should work fine. Waiting for your feedback.

**Comment by blerohellec** [comment]
Perfect. Thx
