### ISSUE TITLE
Pb with profile at plugin install

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/simcard#24]
1.4 (0.85)
See #23 

At installation, it creates 2 records in table glpi_profilerights for the current profile.
- one where name = simcard:simcard, rights = 31. It corresponds to Read/update/create/delete/purge rights
- one where name = simcard:open-ticket, rights = 1, which is useless and will never be used.

Only 1 record must be created, where name = simcard:simcard and rights = 63. It corresponds to all possible rights

**Comment by dethegeek** [comment]
bug linked to #23, closed too

**Comment by blerohellec** [comment]
OK.
