### ISSUE TITLE
Link with problems

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/simcard#26]
1.4 (0.85) but also previous version
A Simcard which can be associated to a ticket can also be associated to a problem.
Indeed, one can associate a Simcard to a problem. The simcard appears in the 'Items' tab of the problem.
To be consistent, a Simcard should have a Problems tab, just like it has a Tickets tab (when Associable to a ticket)

**Comment by btry** [comment]
I'm waiting for your review.

**Comment by blerohellec** [comment]
OK
