### ISSUE TITLE
'Simcard' of a computer/device/phone : link 'New SIM card' don't go through template

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/simcard#27]
1.4 for 0.85
In 'SIM cards' tab of a computer/device, there is a link name 'New SIM card' to create a SIM card.
But it does not propose first the list of Simcards template.

**Comment by btry** [comment]
I think this link should be removed : 
- We may consider this a a new feature,
- I believe this way to create a simcard differs to the general way to work in GLPI
- this is complex to implement without doing too many ugly hacks

**Comment by blerohellec** [comment]
I fully agree : remove it.
