### ISSUE TITLE
0.90 version

### ISSUE THREAD

**Issue by orthagh** [pluginsGLPI/simcard#28]
Version 1.4.1 asks for a [0.85,<0.86] version.   
Could you extends checks to [0.85,<0.91] ?   

In our glpi roadmap, we have a prerequisite to stabilize plugin api, so i think we can remove PLUGIN_SIMCARD_GLPI_MAX_VERSION check

**Comment by btry** [comment]
Compatibility limit raised to GLPI 0.90
