### ISSUE TITLE
Table glpi_profiles is not cleaned at unistall

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/simcard#31]
v1.4.1 (GLPI 0.85)
If the itemtype Simcards was added to the list of items associable to a ticket (Profile > tab Assistance), "PluginSimcardSimcard" was added to glpi_profiles.helpdesk_item_type (text string).
On Uninstall, it's not removed !
If it doesn't exist yet, I think that GLPI (core) has to provide a method to do this.

**Comment by btry** [comment]
I noticed the checkbox "assignable to a ticket" found in profile > tab simcard duplicates the same feature in GLPI's core.

This needs a rewrite. Removal of this checkbox planned to let GLPI manage this featire itself.

**Comment by blerohellec** [comment]
I do not agree with the fact that one duplicates the other. I consider they are 2 different things.

**Comment by btry** [comment]
As I added to my last comment, there are actually 3 things affecting the ability to associate a simcard to a ticket. 

In the simcard plugin :
![capture du 2015-10-08 15 24 33](https://cloud.githubusercontent.com/assets/14139801/10367525/4f1ebdae-6dd1-11e5-8979-507e2f7a7ab7.png)

In GLPI core : 
![capture du 2015-10-08 15 24 05](https://cloud.githubusercontent.com/assets/14139801/10367530/5b7e2364-6dd1-11e5-9862-81fff21b2da9.png)

In a simcard instance : 
![capture du 2015-10-08 15 23 18](https://cloud.githubusercontent.com/assets/14139801/10367537/6720d5b8-6dd1-11e5-9922-5f6e641a9411.png)

In the first two pictures, notice the itemtype simcard is associable to a ticket in the plugin's point of view, but not in GLPI's point of view.

Having this configuration, I'm not able to add a simcard to a ticket (I'm currently having one instance of simcard). If I change the dropdown on the instance to allow ticket association, I'm still not able to associate my instance.

This behavior is in my point of view an inconcistency. If I read the source code, (hook.php, function plugin_simcard_profileRightUpdate() ) I see $_SESSION is updated when the current profile changes; but I did not find anything which updates the helpdesk_item_type list. Either the plugin should fully manage add or delete of its itemtype in this list, either GLPI should do this itself.

I'm waiting for your comment about this.

About the third picture, i need more investigation to find where is the related code. I think this is a different feature to override the controls seen in the previous screenshots. Is it really used and useful ? I'm not sure. I'm also not sure it is bug-less. Needs testing.

**Comment by blerohellec** [comment]
Regarding the helpdesk_item_type list, I think it's up to GLPI to manage the complete add/remove of an itemtype supplied by a plugin. GLPI already manages the 'add'. It misses the 'remove'. You should report to GLPI core team.

Regarding the fact that you still can't associate a Simcard instance to a ticket when you change its 'associable items to a ticket' from No (default value at creation) to Yes -> I don't have this behaviour. For me, it works fine.

**Comment by btry** [comment]
First point : I agree, and that's why I think the checkbox "associable to a ticket" should go away in the first screenshot. As GLPI does not provide anything to add/remove an itemtype from helpdesk_item_type and the API shall not change in GLPI 0.90.x, I'm expecting this feature will be rejected, and may be added in next major release. For now, the plugin should manage helpdesk_item_type itself.

Second point : I think helpdesk_item_type has been altered womeway while I was debugging / porting the plugin. I remember helpdesk_item_type contained PluginSimcardSimcard in my current profile, but now, I cannot reproduce it. I believe it has been added due to an edit on my profile. I have to test several scenarios to find out how this actually happened.

If we agree about the first point and I reimplement the related feature, the new implementation may resolve the second point.

**Comment by blerohellec** [comment]
First point : it's a very minor bug, and all the plugins supplying special itemtypes are concerned. I suggest you don't waste time in developping a temporary workaround. Let the GLPI core team propose a definite solution.

**Comment by trasher** [comment]
@blerohellec did you open an ticket against GLPi core concerning this issue? You can reference the present ticket using the `pluginsGLPI/simcard#31` syntax.
