### ISSUE TITLE
sql error when deleting a profile

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/simcard#32]
v 1.4.1 (GLPI 0.85)
Delete permanently a profile and I get a Sql error; it looks for table glpi_plugin_simcard_profiles, that no longer exists in GLPI 0.85.

 *** MySQL query error:
  SQL: SELECT * FROM `glpi_plugin_simcard_profiles` WHERE profiles_id=15
  Error: Table 'glpi085.glpi_plugin_simcard_profiles' doesn't exist
  Backtrace :
  inc/dbmysql.class.php:778                          
  inc/dbmysql.class.php:532                          DBmysqlIterator->__construct()
  inc/commondbtm.class.php:559                       DBmysql->request()
  inc/commondbtm.class.php:484                       CommonDBTM->cleanRelationData()
  inc/commondbtm.class.php:1330                      CommonDBTM->deleteFromDB()
  front/profile.form.php:53                          CommonDBTM->delete()

**Comment by blerohellec** [comment]
error still present

**Comment by btry** [comment]
should be OK, now

**Comment by blerohellec** [comment]
Corrected. Thx
