### ISSUE TITLE
Dropdown bookmarks are not cleaned at plugin uninstall

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/simcard#33]
v1.4.1 (GLPI 0.85)
At plugin uninstall, the bookmarks related to the 4 dropdowns are not deleted from table glpi_bookmarks (glpi_bookmarks_users).

**Comment by btry** [comment]
I guess I should also check glpi_bookmarks

**Comment by blerohellec** [comment]
Corrected. Thx
