### ISSUE TITLE
Datainjection : Notes are not created

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/simcard#34]
v1.4.1 (0.85) && plugin DataInjection v2.4.1
Create a model where a column of the entry csv file maps a Note. Or where an 'additionnal information' maps a Note.
In both cases, no note is created by the Injection process

**Comment by btry** [comment]
I compared how the plugin works with computers. Datainjection does not provide a way to populate notepad for this asset.

I think Datainjection should not provide this field for simcards as well. I suggest removal of this feature in Simcard if possible.

**Comment by blerohellec** [comment]
Agreed. Remove Notes from datainjection for Simcard.
