### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/simcard#35]
Hello,

After installation 1.4.1 on GLPI 0.90 error message access denied.

only tools and plugin menu are available. Interface comes back to english if I am in french.

**Comment by btry** [comment]
Hi

I can reproduce the bug only on the latest revision on GLPI 0.90. If I test on the latest release (tag 0.90) the bug does no longer occur.

Do you confirm you're using the bleeding edge of GLPI 0.90 branch ?

**Comment by btry** [comment]
I think I found the issue. Please update the plugin and feedback how it works.

**Comment by satyan01** [comment]
The issue is solved but I don't see data anymore even if they are in the database

**Comment by dethegeek** [comment]
Indeed, There are fome more thigs to fix : cannot create an item too.

**Comment by btry** [comment]
I searched an fix the bug using a fresh installation of GLPI and simcard. If I create a new simcard, I'm able to show it in the list, and view it.

As the issue affected GLPI's session (that's why you lost all menus, and language preference), I guess you need to logout and login again.

**Comment by satyan01** [comment]
Yes But I would like to see the simcard in my database. They come from 0.85.2 migration and It has worked before yesterday glpi master branch

**Comment by btry** [comment]
Then you're able ti create a simcard, view it, but you're unable to see previously created ones ?

**Comment by picaro04** [comment]
Hi,

I have installed the simcard-plugin 1.4.1 on glpi 0.85.2. After activating simcards I saw no  data for any PC. The PCs are in the database and they are shown in the list but by clicking on one item (any PC or server) I see only the menue of glpi, the rest of the page is empty.

After deactivating the plugin simcards everything works fine .

 

Regards

Peter

 

Von: btry [mailto:notifications@github.com] 
Gesendet: Freitag, 16. Oktober 2015 09:14
An: pluginsGLPI/simcard
Betreff: Re: [simcard] Access Denied (#35)

 

Then you're able ti create a simcard, view it, but you're unable to see previously created ones ?

**Comment by satyan01** [comment]
Creation is ok and the view ok, but not my existing data before last version

**Comment by btry** [comment]
@picaro04 : Got it : this is an other issue (#36) : the plugin used a method wich exists since GLPI 0.90. Please, test the latest revision and write your feedback on this new issue.

**Comment by btry** [comment]
@satyan01 : I created a fresh GLPI 0.85.2, added a simcard item, upgraded to GLPI master. I can list and view the simcard. 

If you're not using a super-admin profile, can you test using it ?

**Comment by satyan01** [comment]
I have tried with technician profile and I can't see my simcards items from 0.85.2. Only the last new created one.

**Comment by satyan01** [comment]
I am going to install from zero glpi 0.90 branch master and migrate my 0.85.2 database.
