### ISSUE TITLE
Under GLPI 0.85.2 cannot view computers if simcard pluginactive

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/simcard#36]
see picaro04's post in #35

**Comment by picaro04** [comment]
we use more plug-ins, so I can´t install glpi 0.90. Only when fusioninventory-for-glpi in a version for glpi 0.90 published is, we can upgrade.

**Comment by btry** [comment]
Simcard 1.4 is intended to be compatible with both GLPI 0.85 and 0.90. Upgrading only the plugin should be sufficient to fix the regression you discovered.

**Comment by btry** [comment]
@picaro04 : you did not feedback about the fix, I guess it worked for you. If not, feel free to open a new ticket.
