### ISSUE TITLE
Add the possibility to link Simcard to Networkequipment object (+printer)

### ISSUE THREAD

**Issue by C-Duv** [pluginsGLPI/simcard#37]
Currently (as of GLPI v0.90 and Simcard v1.4.1), a `simcard` object can only be linked to `computer`, `peripheral` or `phone` objects.

Some of my `networkequipment` devices have cellular network capabilities (eg. mobile broadband + WiFi devices) so, in a thorough inventorying process, I would like to link the SIM cards to theses network devices.

Bonus: I know (but don't use one) some printers also have a SIM card to perform reporting via cellular networks. Maybe the `simcard`-`printer` link possibility should be added too?

**Comment by btry** [comment]
similar question #41 

You may try to patch simcard. Open simcard/inc/simcard_item.class.php and find the getClasses() method. Add in the returned array the itemtypes you need.

You will have to re apply this patch each time you upgrade, until simcard natively implements something to satisfy your need.

**Comment by C-Duv** [comment]
Thanks, I added `'Networkequipment'` to the array and it works : I was able to link a `simcard` to a `networkequipment` (from the `simcard` object form).

But on the `networkequipment` object form the linked *Simcards* tab is not shown (to list the `simcard` linked to the `networkequipment`: Where should I look to change the code so could I make the tab appears?

**Comment by btry** [comment]
Ah, yes, there is also something to do to add a new tab on a network equipment and show the new relation. I will update the plugin to fill your needs soon.

**Comment by C-Duv** [comment]
Great!

But I can also try to fix it on my side and open a PR if you want.

**Comment by btry** [comment]
Indeed you're welcome to contribute.

I checked and the missing tabs should appear without any further change (see simcard/setup.php, line 63). Try logout and login again, this issue is maybe due to a session variable not updated.

**Comment by btry** [comment]
The main change has been pushed. All new needed tabs appear immediately (using GLPI 0.90.x and master branch of Simcards).

Which versions of GLPI and Simcard are you using ?

**Comment by C-Duv** [comment]
I have GLPI v0.90 and Simcard v1.4.1.
The *Simcards* tab **did** appeared on printers
but did not on networkequipments: I suspect a buggy plugin, I'll check on a clean GLPI install.

**Comment by C-Duv** [comment]
Tested on GLPI v9.1 and Simcard v1.4.2: It works on networkequipments.
