### ISSUE TITLE
plugins simcard 1.4.1 et genericobject 0.85-1.0 pour GLPI 0.90

### ISSUE THREAD

**Issue by sebfun** [pluginsGLPI/simcard#41]
Bonjour

J'utilise ces 2 plugins très bien et j'ai trouvé un petit défaut avec simcard.

En effet, lorsque je créé des nouveaux types d'objets (ex : tablettes, tel mobile, etc), dans la gestion des cartes sim, dans Eléments rattachés, il n'est pas possible de les rattacher ce qui est bien dommage. Je ne peux rattacher que les types suivants : Téléphone, Ordinateur ou Périphérique

Seulement voilà, les nouveaux types d'objets ne sont pas dans une de ces 3 catégories d'objets ce qui est normal puisqu'il s'agit d'un nouveau type d'objets.

Le problème est que dans la gestion des cartes sim je ne peux pas faire le rattachement ad hoc

Je joins 2 images pour montrer :

Gestion carte sim Eléments rattachés : http://www.cjoint.com/c/EKsn0BQ5qOk
et

Menu PARC (montrant les différents types d'objets créés) : http://www.cjoint.com/c/EKsn6ks2wVk

Où sinon quel(s) fichier(s) à modifier ?

**Comment by btry** [comment]
Bonjour

Votre demande est proche de #37.

Dans simcard/inc/simcard_item.class.php il y a une méthode getClasses(). Elle retourne un array des types liables à une carte SIM.

Si vous ajoutez les itemtypes créés par Generic objects, ça devrait fonctionner. Generic Object crée des classes pour ses nouveaux itemtypes, Ce sont ces noms de classe qu'il faut utiliser. Cherchez dans glpi/files/_plugins/genericobject/ .

Attention cependant : lors d'un update du plugin, le changement dans le code sera perdu et il faudra réappliquer la modification.

**Comment by sebfun** [comment]
en fait ce n'est pas comme la demande 37 car la demande 37 concerne des équipements réseaux. C'est un type d'objet qui est déjà intégré à GLPI. Moi dans mon cas, Generic Object créé de nouveaux types d'objets.
Je préfère utiliser la solution que l'on m'a proposé sur le forum de GLPI à savoir : se servir du type d'objet "Téléphones" ce qui me permet de lier les cartes sim :+1:

**Comment by sebfun** [comment]
par contre j'en profite pour indiquer que dans carte sim il n'existe pas de champ Numéro de série. Ce qui est dommage car toutes les cartes SIM en sont équipées généralement ça commence par 89331032. C'est un numéro à 20 chiffres. Il serarit peut-être intéressant de le rajouter car du coup je l'ai mis dans le champ "Numéro d'inventaire"

**Comment by btry** [comment]
Il y a 2 tickets #38 et #40 qui concernent de près ou de loin le numéro de série. Pour les résoudre, il y a un travail de documentation à faire, je n'ai pas encore la certitude que les deux tickets concernent des champs différents ou identiques. 

Je clos donc ce ticket et vous invite à suivre les deux autres, plus appropriés, pour cette nouvelle demande.
