### ISSUE TITLE
association with simcard from phone loading failed

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/simcard#47]
Hello

When I want to associate a simcard from a phone in the dropdown list of simcard i have "loading falied".

From simcard to associate phones it works

Debug mode :+1: 

	SELECT `glpi_phones`.* 
FROM `glpi_phones` 
WHERE `glpi_phones`.`id` = '72' LIMIT 1	0.000	 
33	SELECT * 
FROM `glpi_plugin_simcard_simcards_items` 
WHERE `items_id` = '72' AND `itemtype`='Phone'	0.000	 
34	SELECT `glpi_plugin_simcard_simcards`.* 
FROM `glpi_plugin_simcard_simcards` 
WHERE `glpi_plugin_simcard_simcards`.`id` = '92' LIMIT 1	0.000	 
35	SELECT `glpi_entities`.`completename`, '' AS transname, `glpi_entities`.`comment`, '' AS transcomment 
FROM `glpi_entities` 
WHERE `glpi_entities`.`id` = '1'	0.000	 
36	SELECT `id` 
FROM `glpi_plugin_simcard_simcards` 
WHERE `is_template`='0' AND `id` IN (SELECT `plugin_simcard_simcards_id` 
FROM `glpi_plugin_simcard_simcards_items`)

**Comment by wimaerts** [comment]
We have the same problem with our setup. With fiddler i can see the message "414 Request-URI Too Long". I tried to change some apache parameters, but without luck so far.

**Comment by GoempieK** [comment]
Same here

**Comment by satyan01** [comment]
It seems to come from GLPI not simcard plugin
