### ISSUE TITLE
Cannot link SIMCard to ticket

### ISSUE THREAD

**Issue by Eurorail** [pluginsGLPI/simcard#55]
Hi,

I recently installed SimCard 1.4.2 on GLPI 0.90.5. 

I added some SIM cards with option to make them linkable to a ticket. It worked for some time but now I can't link a ticket to a SIM card anymore. 

In a ticket, under the "Items" menu, SimCARD items are not proposed in the list (only Computer, Custom Device, Monitor, Network Device, Phone, Printer and Software). 

Tried to desactivate/reactivate the plugin but it didn't solve the problem. Can someone help me please ?

Thank you.

**Comment by Eurorail** [comment]
UP,

Any help someone ? 

Thanks forward.

**Comment by btry** [comment]
Hi

Did something change in your GLPI before the feature breaks ? An upgrade of Simcards ? an isntall or an upgrade of GLPI or an other plugin ?

**Comment by Eurorail** [comment]
I installed nothing else this since plugins. Neither any update on the OS.
I tried to uninstall and reinstall the plugin : I get the feature back but I lost all my SIM cards. Prior to this I took a snapshot of the VM, so I reverted to this snapshot to get my SIM cards back and I still have to deal with the problem.

**Comment by btry** [comment]
If you uninstall the plugin, it will delete its tables, then it is normal you loose your simcards. Hopefully you got a backup ;) 

It looks interesting the feature works until you restored your simcards. 

You should reproduce the bug then check your logs in glpi/files/_log : php-errors.log sql-errors.log. 

Check also the error log of your HTTP server in case there is an HTTP 500 error.

**Comment by Eurorail** [comment]
I meant I restored the Virtual Machine to a previous state (before unintalling/reinstalling the plugin) to get my SIM cards back.

Maybe I should try to first save my databases, uninstall/reinstall the plugin and then restore the database ? But the existing links between SIMcards and tickets or phones will be kept ?

**Comment by btry** [comment]
Check in the profile of your user : maybe the simcards are not in the helpdesk types

Administration > profiles > (your profile) > tab Assistance > section Association.

**Comment by Eurorail** [comment]
Yes perfect it worked ! 
But I can't figure out why the SIMCards were not in the helpdesk types as it worked before and I never modified my profile.

Anyway, problem is now solved. Thank you and kind regards,

**Comment by btry** [comment]
Great the problem is solved for you, but not for the plugin : I guess at install time the simcard type is added in the helpdesk types, without being added in the saved profile settings in DB. 

I have to reopen.

**Comment by Eurorail** [comment]
Do you need me some log files to help troubleshooting ?

**Comment by btry** [comment]
Yes, if you got something relevant, this might help me. Thank you very much.

**Comment by Eurorail** [comment]
I don't know which log files to send and if they are relevant or not.
Can you tell me which log files i should send ?

**Comment by btry** [comment]
Of course : GLPI maintains logs in glpi/files/_log/

- php-errors.log for PHP related errors
- sql-errors.log for SQL related errors

If you want to report a bug to GLPI or a plugin, it is nice to check them and show the relevant entries.

**Comment by Eurorail** [comment]
I'll have a look to see if I find some relevant entries. And will send it to you if I find some.

**Comment by btry** [comment]
Hi

I think I found your issue : when the you install the plugin, your session is updated and adds the simcard as a helpdesk itemtype. THis is equivalent to the change which solved your issue. However it is not saved in  the database. 

After a logout / login cycle, your session is reseted, and you lost the simcard in the helpdesk itemtypes, then you're no longer allowed to link a simcard to a ticket. 

If you apply the following patch, you should no longer need to update the helpdesk itemtypes.

https://github.com/pluginsGLPI/simcard/compare/develop...btry:feature/fix_helpdesk_itemtype_after_install?expand=1

I would appreciate you test it and feedback.

**Comment by Eurorail** [comment]
Hi,

since the change you suggested me to do, I don't have the problem anymore. It occurred only since the installation.
Should I apply the patch anyway ?

Best regards,

**Comment by btry** [comment]
Hi

No, you don't need the patch becasue we manually did the missing action in the installation of the plugin.

I simply wish, if you can, that you run the installation of the plugin on a testing environment to confirm the patch solves the bug you found.

**Comment by Eurorail** [comment]
Just tested in a test env, I can link the SIM to a ticket with no problem :)
Thanks :+1:

**Comment by btry** [comment]
Thank you for your feedback.
