### ISSUE TITLE
[GLPI 9.2] - Migrate Simcards into GLPI's component 

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/simcard#61]
Component Simcards ~~should be~~ is merged and available in GLPI 9.2.

The plugin must say good bye and provide a migration tool to GLPI's implementation.

**Comment by dithe** [comment]
After migration to 9.2 do I need to uninstall plugin?

**Comment by btry** [comment]
Hi

Do you have valuable data in this plugin ?

**Comment by dithe** [comment]
No I don't and I uninstalled plugin, but after that I don't have sim cards in assets.

**Comment by btry** [comment]
That's normal. In GLPI the simcards are not an asset, they are a component.

Navigate to Setup > Components
![image](https://user-images.githubusercontent.com/14139801/31563685-7166ca90-b060-11e7-84c4-f429f31bd741.png)

Choose Simcards
![image](https://user-images.githubusercontent.com/14139801/31563688-74adfdc2-b060-11e7-94ce-4db0877b986b.png)

**Comment by dithe** [comment]
I've got it. Thank you.

**Comment by btry** [comment]
Ok, so I close.

**Comment by AlgamGCA** [comment]
Hi, I have done the upgrade to 9.2 and I can't find a way to migrate data from simcard plugin to new simcard components.
It is possible?
