### ISSUE TITLE
Drop deprecated usage

### ISSUE THREAD

**Issue by trasher** [pluginsGLPI/simcard#62]
Plugin uses `openArrowMassive` and `closeArrowMassve` methods that are deprecated. See https://github.com/glpi-project/glpi/issues/2394

**Comment by btry** [comment]
Is this needed as the simcards are now in the core ? Should we not focus on migration ?

**Comment by trasher** [comment]
I've just grep-ed in my plugins directory and opened issues against all plugins I've found ;)

Closing as not relevant. BTW, you should add a warning telling this has been integrated in the core ;)

**Comment by btry** [comment]
Agreed
