### ISSUE TITLE
[GLPI 9.2] Migration from simcard plugin

### ISSUE THREAD

**Issue by AlgamGCA** [pluginsGLPI/simcard#65]
Hi, I have made upgrade to glip 9.2, how can I migrate data from simcard plugin?
Thanks

**Comment by btry** [comment]
Hi

Currently there is no migration tool yet. Plugins are maintained at best effort.

You can speed up development of this tool by sponsoring it. If you're interested, please contact us at contact@teclib.com .

**Comment by AlgamGCA** [comment]
Ok, maybe this will be possible in future update of glpi 9.2.
I close this issue.
Thanks
