### ISSUE TITLE
Simcard plugin in GLPI 9.3

### ISSUE THREAD

**Issue by mnitka** [pluginsGLPI/simcard#73]
Hi,
I know that in GLPI 9.3 simcards are available as components but it is useless!
Reasons:
1. Complicated
2. Imposible import with Data Injection Plugin
3. I want to assign simcard to people, not only phones

Is possible to make this plugin working on GLPI 9.3? This plugin was just better

**Comment by trasher** [comment]
1 => maybe you should propose/participate to enhance?
2 => it's a datainjection issue
3 => same as 1.

**Comment by mnitka** [comment]
1, 3 -> I saw some discuss about it but with no positive conclusions. 
2 -> I reported this issue on DataInjection github and official GLPI forum but with no resposne.

Of course I can import simcards with SQL and use build-in simcards but in my opinion earlier method was better.
Is any way to force this plugin to be activated in 9.3.1?

**Comment by btry** [comment]
Hi

The develop branch should work with GLPI 9.2 and 9.3, however there will be no support for the plugin.

I join @trasher comment: tell us how you think the core implementation could be better. We are listening to your suggestions. Writing code is not the only way to contribute.

**Comment by mnitka** [comment]
Hi,

Plugin works fine with GLPI 9.3. Thanks for replying.

Regards
